site_name: AI Startup 
#repo_url: https://github.com/Insper/ai_startup/
#repo_name: AI Startup
#site_url: https://insper.github.io/ai_startup/

theme:
    name: 'material'

extra_css:
  - css/custom.css

nav:
  - 'Home': 'index.md'
  - 'Ementa': 'ementa.md'
  - 'Plano de Aula': 'plano_de_aulas.md'
  - 'Etapas': 'etapas.md'
  - 'Avaliação': 'avaliacao.md'
  - 'Aulas':
    - 'Empreendedorismo':
      - 'aulas/empreendedorismo/index.md'
  #  - 'Impacto':
  #    - 'aulas/02_empreendedorismo/index.md'
  #  - 'Como desenvolver':
  #    - 'aulas/02_empreendedorismo/index.md'
  #  - 'Desenvolvendo':
  #    - 'aulas/02_empreendedorismo/index.md'
  - 'Referências': 'referencias.md'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: "docs/_snippets"
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes

plugins: 
  - git-revision-date-localized
  - mkdocs-jupyter



